
package com.forkexec.rst.domain;

import com.forkexec.rst.ws.BadInitFault;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BadInitFault", targetNamespace = "http://ws.rst.forkexec.com/")
public class NoSuchMenuFaultException
    extends Exception
{

    public NoSuchMenuFaultException() {
    }

    public NoSuchMenuFaultException(String message) {
        super(message);
    }

}
